### ISSUE TITLE
Not worked, whats wrong

### ISSUE THREAD

**Issue by hakancunier** [cfanatic/ocr-receipt#1]
Here is the output,

docker exec -it ocr-receipt ../misc/build.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /src/ocr/build
ninja: no work to do.
Test project /src/ocr/build
      Start  1: configuration_test.shops
 1/13 Test  #1: configuration_test.shops .................   Passed    0.13 sec
      Start  2: configuration_test.filters
 2/13 Test  #2: configuration_test.filters ...............   Passed    0.13 sec
      Start  3: configuration_test.easyocr
 3/13 Test  #3: configuration_test.easyocr ...............   Passed    0.13 sec
      Start  4: configuration_test.tesseract_paddings
 4/13 Test  #4: configuration_test.tesseract_paddings ....   Passed    0.13 sec
      Start  5: configuration_test.tesseract_threshold
 5/13 Test  #5: configuration_test.tesseract_threshold ...   Passed    0.13 sec
      Start  6: engine_easyocr_test.receipt_1
 6/13 Test  #6: engine_easyocr_test.receipt_1 ............***Exception: SegFault 52.22 sec
      Start  7: engine_easyocr_test.receipt_2
 7/13 Test  #7: engine_easyocr_test.receipt_2 ............***Exception: SegFault 51.11 sec
      Start  8: engine_tesseract_test.receipt_1
 8/13 Test  #8: engine_tesseract_test.receipt_1 ..........***Failed   16.81 sec
      Start  9: engine_tesseract_test.receipt_2
 9/13 Test  #9: engine_tesseract_test.receipt_2 ..........***Failed    0.62 sec
      Start 10: receipt_test.receipt_1
10/13 Test #10: receipt_test.receipt_1 ...................***Exception: SegFault  1.13 sec
      Start 11: receipt_test.receipt_2
11/13 Test #11: receipt_test.receipt_2 ...................***Exception: SegFault  1.14 sec
      Start 12: receipt_test.receipt_3
12/13 Test #12: receipt_test.receipt_3 ...................***Exception: SegFault  1.14 sec
      Start 13: receipt_test.receipt_4
13/13 Test #13: receipt_test.receipt_4 ...................***Exception: SegFault  1.14 sec

38% tests passed, 8 tests failed out of 13

Total Test time (real) = 133.08 sec

The following tests FAILED:
          6 - engine_easyocr_test.receipt_1 (SEGFAULT)
          7 - engine_easyocr_test.receipt_2 (SEGFAULT)
          8 - engine_tesseract_test.receipt_1 (Failed)
          9 - engine_tesseract_test.receipt_2 (Failed)
         10 - receipt_test.receipt_1 (SEGFAULT)
         11 - receipt_test.receipt_2 (SEGFAULT)
         12 - receipt_test.receipt_3 (SEGFAULT)
         13 - receipt_test.receipt_4 (SEGFAULT)
Errors while running CTest
Output from these tests are in: /src/ocr/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

**Comment by rissato** [comment]
I have the same issue.

**Comment by cristian-sima** [comment]
same here @cfanatic any help?

**Comment by fxnm** [comment]
Its an issue with [EasyOCR](https://github.com/JaidedAI/EasyOCR) and [Pillow](https://github.com/python-pillow/Pillow).
To fix the issue set `Pillow==9.5.0` in the Dockerfile ([Issue](https://github.com/JaidedAI/EasyOCR/issues/1077)).

**Comment by cfanatic** [comment]
Fix is provided with [https://github.com/cfanatic/ocr-receipt/commit/984b656374aca43369c03a020ad1cf1969ac85c7](https://github.com/cfanatic/ocr-receipt/commit/984b656374aca43369c03a020ad1cf1969ac85c7).

Thanks a lot @fxnm.
